#!/bin/env perl

use v5.38;
use utf8;
use strict;
use FindBin;

sub format_uint128($v) {
    unless ($v =~ /^([0-9a-fA-F]{16})([0-9a-fA-F]{16})$/) {
        die "Invalid uint128: $v";
    }
    my ($h, $l) = ($1, $2);
    return sprintf("Float128{0x%s, 0x%s}", $h, $l);
}

# f64_to_f128.txt is generated by TestFloat-3b/testfloat_gen.
# http://www.jhauser.us/arithmetic/TestFloat.html
# $ ./testfloat_gen -level 1 f64_to_f128 > f64_to_f16.txt
open my $fh, "<", "$FindBin::Bin/f64_to_f128.txt" or die "Can't open f64_to_f128.txt: $!";

say <<EOF;
// Code generated by scripts/f64_to_f128.pl; DO NOT EDIT.

package float128

var f64ToF128 = []struct {
    f64  uint64
    f128 Float128
} {
EOF
while(my $line = <$fh>) {
    chomp $line;
    my ($a, $b, undef) = split /\s+/, $line;
    printf("{0x%s, %s},\n", $a, format_uint128($b),);
}

say "}";

close $fh;
