name: test
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.21"
        arch:
          - amd64
          - "386"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: |
          if [ "$GITHUB_REF" = "refs/heads/main" ]; then
            go test -coverprofile="coverage.txt" -timeout 1h -v ./...
          else
            go test -coverprofile="coverage.txt" -timeout 10m -short -v ./...
          fi
        env:
          GOARCH: ${{ matrix.arch }}
      - name: upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          flags: ${{ matrix.go }}
