name: testfloat
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - f128_to_f64
          - f64_to_f128
          - f128_mul
          - f128_div
          - f128_add
          - f128_eq
          - f128_lt
          - f128_le
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: latest
      - run: |
          ./scripts/build_test_float.sh
          ./scripts/run_test.sh ${{ matrix.test }}
